=== RaphaelPrevost/Back2Shops/users/files/invoice/invoice.dtd
<!ENTITY % INVOICE.version "-//BACKTOSHOPS//INVOICE" >
<!ENTITY % NS.prefixed "IGNORE" >
<!ENTITY % INVOICE.prefix "invoice" >
<!ENTITY % INVOICE.global.attrs.prefixed "INCLUDE" >

<?doc type="doctype" role="title" { BackToShops Invoice } ?>

<!-- root -->
<!ELEMENT invoices (invoice+) >
<!ATTLIST invoices version CDATA #REQUIRED >

<!-- invoice -->
<!ELEMENT invoice (seller, buyer, item+, shipping, total, payment?) >
<!ATTLIST invoice number CDATA #REQUIRED
                  currency CDATA #REQUIRED
                  date CDATA #REQUIRED >

<!-- seller -->
<!ELEMENT seller (name, img, id+, address) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT img (#PCDATA) >

<!ELEMENT id (#PCDATA) >
<!ATTLIST id type (business | tax | personal) "business" >

<!ELEMENT address (addr, zip?, city, province, country) >
<!ELEMENT addr (#PCDATA) >
<!ELEMENT zip (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT province (#PCDATA) >
<!ELEMENT country (#PCDATA) >
<!ATTLIST country province CDATA #IMPLIED >

<!-- buyer -->
<!ELEMENT buyer (name, address) >

<!-- items -->
<!ATTLIST item id CDATA #REQUIRED >
<!ELEMENT item (name?, desc, price, qty, premium, tax*, subtotal, detail?) >
<!ELEMENT desc (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ATTLIST price original CDATA #IMPLIED >
<!ELEMENT qty (#PCDATA) >
<!ELEMENT premium (#PCDATA) >
<!ELEMENT tax (#PCDATA) >
<!ATTLIST tax name CDATA #REQUIRED
              amount CDATA #REQUIRED
              to_worldwide CDATA #REQUIRED
              show CDATA #REQUIRED>
<!ELEMENT subtotal (#PCDATA) >
<!ELEMENT detail (subitem+) >
<!ELEMENT subitem (desc, qty) >

<!-- shipping fees -->
<!ELEMENT shipping (period?, desc?, postage?, handling?, tax?, subtotal) >
<!ELEMENT postage (#PCDATA) >
<!ELEMENT handling (#PCDATA) >

<!ELEMENT total (#PCDATA) >
<!ATTLIST total gross CDATA #IMPLIED
                tax CDATA #IMPLIED >

<!ELEMENT payment (period?, penalty?, instructions?) >
<!ELEMENT period (#PCDATA) >
<!ELEMENT penalty (#PCDATA) >
<!ELEMENT instructions (#PCDATA) >

=== RaphaelPrevost/Back2Shops/backtoshops/webservice/templates/invoice.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE invoices PUBLIC "-//BACKTOSHOPS//INVOICE" "invoice.dtd">
<invoices version="1.0">
    {% for object in object_list %}
        <!-- invoice -->
        <invoice number="{{ object.number }}"
                 currency="{{ object.currency }}"
                 date="{{ object.date }}">
            <!-- seller -->
            <seller>
                <name>{{ object.seller.name }}</name>
                <img>{{ object.seller.img }}</img>
                {% if object.seller.business %}
                <id type="business">{{ object.seller.business }}</id>
                {% endif %}
                {% if object.seller.tax %}
                <id type="tax">{{ object.seller.tax }}</id>
                {% endif %}
                <id type="personal"></id>
                <address>
                    <addr>{{ object.seller.address.addr }}</addr>
                    <zip>{{ object.seller.address.zip }}</zip>
                    <city>{{ object.seller.address.city }}</city>
                    <province>{{ object.seller.address.province}}</province>
                    <country>{{ object.seller.address.country_name }}</country>
                </address>
            </seller>
            <!-- buyer -->
            <buyer>
                <name>{{ object.buyer.name }}</name>
                {% if object.buyer.company_name %}
                    <company_name>{{ object.buyer.company_name }}</company_name>
                {% endif %}
                {% if object.buyer.company_position %}
                    <company_position>{{ object.buyer.company_position }}</company_position>
                {% endif %}
                {% if object.buyer.company_tax_id %}
                    <company_tax_id>{{ object.buyer.company_tax_id }}</company_tax_id>
                {% endif %}
                <address>
                    <addr>{{ object.buyer.address.address }} {{ object.buyer.address.address2 }}</addr>
                    <zip>{{ object.buyer.address.postalcode }}</zip>
                    <city>{{ object.buyer.address.city }}</city>
                    <province>{{ object.buyer.address.province_name }}</province>
                    <country>{{ object.buyer.address.country_name }}</country>
                </address>
            </buyer>
            <!-- items -->
            {% for item in object.items %}
                <item id="{{ item.id_item}}">
                    {% if item.external_id %}
                        <external_id>{{ item.external_id }}</external_id>
                    {% endif %}
                    <name>{{ item.name }}</name>
                    <type_name>{{ item.type_name }}</type_name>
                    <desc>{{ item.desc }}</desc>
                    <price original="{{ item.price.original }}">{{ item.price.discounted }}</price>
                    <qty>{{ item.qty }}</qty>
                    {% if item.premium > 0 %}
                        <premium>{{ item.premium }}</premium>
                    {% endif %}
                    {% for tax in item.taxes %}
                        <tax name="{{ tax.name }}" amount="{{ tax.amount }}" rate="{{ tax.rate }}" to_worldwide="{{ tax.to_worldwide }}" show="{{ tax.show }}">{{ tax.tax }}</tax>
                    {% endfor %}
                    <subtotal>{{ item.subtotal }}</subtotal>
                    <promo>{{ item.promo }}</promo>
                    <free>{{ item.free }}</free>
                </item>
            {% endfor %}

            <!-- shipping fees -->
            <shipping>
                {% if object.shipping.period %}
                    <period>{{ object.shipping.period }}</period>
                {% endif %}
                {% if object.shipping.desc %}
                    <desc>{{ object.shipping.desc }}</desc>
                {% endif %}
                {% if object.shipping.shipping_fee %}
                    <postage>{{ object.shipping.shipping_fee}}</postage>
                {% endif %}
                {% if object.shipping.handling_fee %}
                    <handling>{{ object.shipping.handling_fee }}</handling>
                {% endif %}
                {% for tax in object.shipping.taxes %}
                    <tax name="{{ tax.name }}" amount="{{ tax.amount }}" rate="{{ tax.rate }}" to_worldwide="{{ tax.to_worldwide }}" show="{{ tax.show }}">{{ tax.tax }}</tax>
                {% endfor %}
                <subtotal>{{ object.shipping.subtotal }}</subtotal>
            </shipping>

            <total items_gross="{{ object.total.items_gross }}" shipping_gross="{{ object.total.shipping_gross }}" gross="{{ object.total.gross }}" tax="{{ object.total.tax }}">{{ object.total.total }}</total>

            <payment>
                {% if object.payment.period %}
                    <period>{{ object.payment.period }}</period>
                {% endif %}
            </payment>

        </invoice>
    {% endfor %}
</invoices>
